In [1]:
import numpy as np
from random import randint
matrix1 = np.empty((12,12), int)
matrix2 = np.empty((12,12), int)

for i in range(0, 12):
    for j in range(0,12):
        matrix1[i][j] = randint(0,100)
        matrix2[i][j] = randint(0,100)
print(matrix1)

optional_row = matrix1[1]
optional_col = matrix1[:, 4]

print(optional_row)
print(optional_col)

print(matrix1[matrix1 > 5])

[[ 51  70  12  30  92  93  73  52  51  48  64  85]
 [ 43  81  28  46  22  76  65  99  41  76   5  81]
 [ 64  95  62  99  57  87  56   8  50  41  16  99]
 [ 71  74  33  45  97  16   6  22  60  29  71  33]
 [ 27  64  83  16  46  17  44  76  52  90  79 100]
 [ 10  47  83  68  11  23  24  33  77  61  43  50]
 [ 73  68  75  26  13  91  59  15  48 100  74  21]
 [ 53  81  11  48  32  27  60  48  74  18  31  46]
 [ 75  52  88  15  81  30  66  73  59  92  61  48]
 [ 80  94  24  90  46  48  16  23  86  15  34  86]
 [ 17  58  85  65  14 100  11  30  91   1  35  91]
 [ 90  39  48  71   6  19  69  29  21  17  69  87]]
[43 81 28 46 22 76 65 99 41 76  5 81]
[92 22 57 97 46 11 13 32 81 46 14  6]
[ 51  70  12  30  92  93  73  52  51  48  64  85  43  81  28  46  22  76
  65  99  41  76  81  64  95  62  99  57  87  56   8  50  41  16  99  71
  74  33  45  97  16   6  22  60  29  71  33  27  64  83  16  46  17  44
  76  52  90  79 100  10  47  83  68  11  23  24  33  77  61  43  50  73
  68  75  26  13  9