In [1]:
import numpy as np

In [11]:
arr1 = np.array([1,2,3,4,5])

In [5]:
arr1.shape

(1, 5)

In [7]:
arr1.dtype

dtype('int32')

In [12]:
arr1.ndim

1

In [16]:
arr1 = np.array([1,2,3,4,5], dtype = np.float)

C:\Users\User\AppData\Local\Temp/ipykernel_13812/3555131695.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4,5], dtype = np.float)


In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr3 = np.arange(0,10,1.5)
arr3

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [20]:
arr_random = np.random.random((10,))

In [21]:
arr_random

array([0.83239054, 0.88074559, 0.39423204, 0.25697418, 0.33596136,
       0.80419844, 0.48988568, 0.30219802, 0.5332662 , 0.2203407 ])

In [22]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr2_sqrt = np.sqrt(arr2)

In [24]:
arr2_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
arr1 = np.arange(10,20)

In [27]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
arr1**2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [29]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
arr1.max()

19

In [31]:
arr1.mean()

14.5

In [32]:
arr1.sum()

145

In [33]:
arr1.std()

2.8722813232690143

In [34]:
arr1 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
arr4 = np.array([4,5,6,7,8,9,10,11,12])

In [36]:
arr4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
arr4.ndim

1

In [38]:
arr4.shape

(9,)

In [40]:
arr4_sqrt = np.sqrt(arr4)

In [41]:
arr4_sqrt

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
       3.        , 3.16227766, 3.31662479, 3.46410162])

In [42]:
np.insert(arr1, 5, 10)

array([10, 11, 12, 13, 14, 10, 15, 16, 17, 18, 19])

In [43]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
np.delete(arr1, 5)

array([10, 11, 12, 13, 14, 16, 17, 18, 19])

In [46]:
arr5 = np.array([1,10,5,33,31])

In [48]:
np.sort(arr5)

array([ 1,  5, 10, 31, 33])

In [49]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr = np.concatenate((arr1,arr2))

In [52]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [54]:
arr[(arr < 5)]


array([0, 1, 2, 3, 4])

In [55]:
arr[(arr < 10) & (arr > 5)]

array([6, 7, 8, 9])

In [56]:
arr[(arr < 3) | (arr > 17)]

array([18, 19,  0,  1,  2])

In [57]:
arr[(arr < 3) & (arr >17)]

array([], dtype=int32)

In [58]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
matrix1.shape



(3, 3)

In [61]:
matrix1.size

9

In [64]:
matrix1.ndim

2

In [65]:
matrix1.reshape(2,6)

ValueError: cannot reshape array of size 9 into shape (2,6)

In [66]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [71]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.empty(2)

array([-2.48929294e-115, -2.72476509e-137])

In [73]:
a = np.empty_like(arr2)

In [74]:
a

array([-1834195408,         484,           0,           0,     6357101,
           7471220,           0,           0,           0,           0])

In [75]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])

In [77]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [78]:
matrix1 + matrix2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [79]:
np.delete(matrix1, 2, axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
[][][] - rows 0
[][][]
[][][]
cols - 1


SyntaxError: invalid syntax (Temp/ipykernel_13812/2773176464.py, line 1)

In [82]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [84]:
matrix2[1,2]

15

In [85]:
matrix2[:,1]

array([11, 14, 17])

In [ ]:
# create 2 matrices with size 12 and 12, 
#add values
#through slicing get an optional row, columnd
#get values which are bigger than 5